# paginable means you can add the ?page=1 param
# limitable means you can add the ?limit=10 param

v1:
  host: "https://api.fishingfrenzy.co/v1"
  routes:
    verify_tokens:
      type: "POST"
      path: "auth/verify-tokens"
      params: "accessToken"

    general: 
      config: 
        type: "GET"
        path: "general-config"

    accessories: # Upgrades Menu & loaded on start
      type: "GET"
      path: "accessories"

    quests:
      type: "GET"
      path: "quests"

    sashimis:
      type: "GET"
      path: "sashimis"

    items:
      type: "GET"
      path: "items" # paginable, limitable 

    fish:
      type: "GET"
      path: "fish" # paginable, limitable 

    pets:
      type: "GET"
      path: "pets" # paginable, limitable 

    # No 404 but empty for now? Might be user rods?
    rods:
      type: "GET"
      path: "rods" # paginable, limitable 

    inventory:
      type:  "GET"
      path: "inventory"

    packages: # Loaded on start
      starter_pack:
        type: "GET"
        path: "packages/starter-pack"

    daily_rewards: 
      type: "GET"
      path: "daily-rewards"

    social_quests:
      type: "GET"
      path: "social-quests" 

      user_quests: 
        type: "GET"
        path: "user-quests" # For now returns a 500?
      mark_as_viewed: 
        type: "POST"
        path: "social-quests/mark-as-viewed" # What's the use of this route?

    referrals: 
      type: "GET"
      path: "reference-code/referrals" # paginable

    events:
      active: 
        type: "GET"
        path: "events/active" # Loaded on start
      switch_theme: 
        type: "GET"
        path: "events/%{eventId}/themes/%{themeId}/switch"

    user_vips:
      type: "GET"
      path: "user-vips" # What's the use of this route?

    users: # Loaded on start
      type: "GET"
      path: "users/me"

    users_all: # I get a forbidden error—from middleware and probably invalid JWT token for this routes
      type: "GET"
      path: "users"

    user: 
      type: "GET" 
      path: "users/67dcc140270b15947cf643de"
      # Is called "mongo id" from error
      # My id is 66cd9ea47605df2d6a9af618 for ex.

    frenzy_points: # Campaign Menu & loaded on start
      type: "GET"
      path: "users/frenzy-points"

    rank: # Rank Menu
      # with ?type=[General/Cooking/Frenzy_point]
      # also pagable like this: startPage= & endPage=
      # also ?tier=None, present with page param above, need to find other values and the use
      type: "GET"
      path: "rank" 

    battle_pass:
      type: "GET"
      path: "battle-pass"