# for type, Skymavis criterias structure = [ { name: "rarity", values: [ "legendary" ] } ]

# CHESTS
chest:
  types:
    common:
      traits:
        - name: "Rarity"
          values: 
            - "Common"
        - name: "Series"
          values: 
            - "Founder"
    common_origins:
      traits:
        - name: "Rarity"
          values: 
            - "Common"
        - name: "Series"
          values: 
            - "Origins"
    rare:
      traits:
        - name: "Rarity"
          values: 
            - "Rare"
        - name: "series"
          values: 
            - "Founder"
    rare_origins:
      traits:
        - name: "Rarity"
          values: 
            - "Rare"
        - name: "Series"
          values: 
            - "Origins"
    epic:
      traits:
        - name: "Rarity"
          values: 
            - "Epic"
        - name: "Series"
          values: 
            - "Sounder"
    epic_origins:
      traits:
        - name: "Rarity"
          values: 
            - "Epic"
        - name: "Series"
          values: 
            - "Origins"
    legendary:
      traits:
        - name: "Rarity"
          values: 
            - "Legendary"
        - name: "Series"
          values: 
            - "Founder"
    legendary_origins:
      traits:
        - name: "Rarity"
          values: 
            - "Legendary"
        - name: "Series"
          values: 
            - "Origins"
# RODS
rod: 
  token_address: "0x77ce5148b7ad284e431175ad7258b54a64816da6"
  